### ISSUE TITLE
未手动指定下载线程时 下载线程为NaN

### ISSUE THREAD

**Issue by pysio2007** [ZeroWolf233/node-openmcim#3]
```
[2024-10-22 21:34:46.541 -0400] INFO (1092878): 正在检查缺失文件
TypeError: Expected `concurrency` to be an integer from 1 and up or `Infinity`, got `NaN` (number)
    at file:///root/node-openmcim/node_modules/p-map/index.js:20:10
    at new Promise (<anonymous>)
    at pMap (file:///root/node-openmcim/node_modules/p-map/index.js:10:9)
    at Cluster.syncFiles (file:///root/node-openmcim/dist/cluster.js:176:15)
    at async bootstrap (file:///root/node-openmcim/dist/bootstrap.js:32:9)
[2024-10-22 21:35:12.835 -0400] INFO (1092878): 缺少 4 个文件，开始同步
[2024-10-22 21:35:12.835 -0400] INFO (1092878): 同步策略 {"source":"center","concurrency":18}
[2024-10-22 21:35:12.838 -0400] INFO (1092878): 您当前的下载线程: NaN
```

**Comment by ZeroWolf233** [comment]
离谱就

**Comment by ZeroWolf233** [comment]
已修，tag 1.1.5，建议更新
